[package]
cairo-version = "=2.10.1"
name = "aqua_stark"
version = "1.5.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
# Development deployment (local katana) via migrate.sh
dev = "./migrate.sh --profile dev"

# Sepolia testnet deployment via migrate.sh (loads .env.sepolia)
sepolia = "./migrate.sh --profile sepolia"

# Dry-run mode for sepolia via migrate.sh
sepolia-dry = "./migrate.sh --profile sepolia --dry-run"

# Build only for sepolia
sepolia-build = "sozo --profile sepolia clean && sozo --profile sepolia build"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
achievement = { git = "https://github.com/cartridge-gg/arcade", tag = "v0.0.0" }
openzeppelin_token = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v1.0.0" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyCreation", 
    "achievement::events::index::e_TrophyProgression", 
]

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }

[profile.sepolia]