[package]
cairo-version = "=2.10.1"
name = "aqua_stark"
version = "1.5.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
# Development deployment (local katana)
dev = "sozo --profile dev clean && sozo --profile dev build && sozo --profile dev migrate"

# Sepolia testnet deployment with environment variables
sepolia = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate --account-address $DOJO_ACCOUNT_ADDRESS --private-key $DOJO_PRIVATE_KEY --fee strk"

# Dry-run mode for sepolia (build and inspect without deploying)
sepolia-dry = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia inspect"

# Build only for sepolia
sepolia-build = "sozo --profile sepolia clean && sozo --profile sepolia build"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
achievement = { git = "https://github.com/cartridge-gg/arcade", tag = "v0.0.0" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyCreation", 
    "achievement::events::index::e_TrophyProgression", 
]

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }

[profile.sepolia]