pub mod CustomErrors {
    pub const NOT_OWNER: felt252 = 'CALLER NOT OWNER';
    pub const AQUARIUM_EMPTY: felt252 = 'AQUARIUM IS EMPTY';
    pub const AQUARIUM_FULL: felt252 = 'AQUARIUM IS FULL';
    pub const INVALID_AQUARIUM_ID: felt252 = 'AQUARIUM WITH ID NOT FOUND';
    pub const FISH_DEAD: felt252 = 'FISH IS DEAD';
    pub const INVALID_FISH_ID: felt252 = 'FISH WITH ID NOT FOUND';
    pub const INVALID_HEALTH: felt252 = 'INVALID HEALTH VALUE';
    pub const INVALID_HUNGER: felt252 = 'INVALID HUNGER VALUE';
    pub const INVALID_GROWTH: felt252 = 'INVALID GROWTH VALUE';
    pub const INVALID_BID: felt252 = 'INVALID BID';
    pub const INVALID_START_PRICE: felt252 = 'INVALID START PRICE';
    pub const END_DATE_IN_PAST: felt252 = 'END DATE IN PAST';
    pub const INVALID_TOKEN: felt252 = 'INVALID TOKEN';
    pub const TOKEN_TRANSFER_FAILED: felt252 = 'TOKEN TRANSFER FAILED';
    pub const CANNOT_CANCEL_AUCTION: felt252 = 'CANNOT CANCEL AUCTION';
    pub const AUCTION_COMPLETED: felt252 = 'AUCTION ALREADY COMPLETED';
    pub const AUCTION_CANCELED: felt252 = 'AUCTION ALREADY CANCELED';
    pub const AUCTION_NOT_ENDED: felt252 = 'AUCTION NOT ENDED';
    pub const AUCTION_ENDED: felt252 = 'AUCTION ENDED';
    pub const ALREADY_REGISTERED: felt252 = 'ALREADY_REGISTERED';
}
