[package]
cairo-version = "=2.10.1"
name = "aqua_stark"
version = "1.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                      # scarb run migrate
spawn = "sozo execute aqua_stark-actions spawn --wait"    # scarb run spawn
move = "sozo execute aqua_stark-actions move -c 1 --wait" # scarb run move

[dependencies]
starknet = "2.9.4"
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.4.0" }
openzeppelin_token = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v1.0.0" }
origami_map = { git = "https://github.com/dojoengine/origami" }


[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.4.0" }
cairo_test = "2.9.4"
