name: Contracts & Frontend CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install asdf
        uses: asdf-vm/actions/setup@v2

      - name: Install plugins
        run: |
          asdf plugin add scarb
          asdf install scarb 2.10.1
          asdf global scarb 2.10.1
          asdf plugin add dojo https://github.com/dojoengine/asdf-dojo
          asdf install dojo 1.5.0
          asdf global dojo 1.5.0
      - name: Build contracts
        run: |
          cd aqua_contract
          sozo build
      - name: Run tests
        run: |
          cd aqua_contract
          sozo test
      - name: Check formatting
        run: |
          cd aqua_contract
          scarb fmt --check

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm format:check

      - name: Run linting
        run: pnpm lint

      - name: Build project
        run: pnpm build
