name: Frontend CI

on:
  push:
    branches: ['main']
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - '.prettierrc'
      - '.prettierignore'
  pull_request:
    branches: ['main']
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - '.prettierrc'
      - '.prettierignore'

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]  # LTS + Current

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            client/node_modules
          key: ${{ runner.os }}-node-modules-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ matrix.node-version }}-
            ${{ runner.os }}-node-modules-

      - name: Cache Vite and TypeScript build outputs
        uses: actions/cache@v4
        with:
          path: |
            client/dist
            client/.vite
            client/node_modules/.vite
            client/tsconfig.app.tsbuildinfo
            client/tsconfig.node.tsbuildinfo
          key: ${{ runner.os }}-build-cache-${{ matrix.node-version }}-${{ hashFiles('client/pnpm-lock.yaml', 'client/vite.config.ts', 'client/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-${{ matrix.node-version }}-
            ${{ runner.os }}-build-cache-

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm format:check
        continue-on-error: true

      - name: Run linting
        run: pnpm lint

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test

      - name: Generate test coverage
        run: pnpm test:coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./client/coverage/coverage-final.json
          directory: ./client/coverage/
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: false

      - name: Build project
        run: pnpm build